# Generated by Django 4.2.15 on 2024-08-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/avatars/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
